/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.3.2-163-g6c414cf8f7"
#endif /* AVUTIL_FFVERSION_H */
